### ISSUE TITLE
중간 피드백) - GitHub Secrets 활용

### ISSUE THREAD

**Issue by annalee8595** [Lee-Hyeongkyeong/OSSW_githubushim#17]
CI/CD 워크플로우(예: GitHub Actions)에서 민감 정보를 안전히 사용하려면:
    
    1. **리포지토리 설정 ▶ Secrets and variables ▶ Actions** 로 이동
    2. **New repository secret** 클릭 후 키/값 등록
        - 예: `FLASK_SECRET_KEY`, `DATABASE_URL`, `MYSQL_ROOT_PASSWORD`
    3. **워크플로우(.github/workflows/ci.yml)** 에서 참조
        
        ```yaml
        yaml
        복사
        name: CI
        
        on: [push, pull_request]
        
        jobs:
          test:
            runs-on: ubuntu-latest
            env:
              DATABASE_URL: ${{ secrets.DATABASE_URL }}
            steps:
              - uses: actions/checkout@v3
              - name: Set up Python
                uses: actions/setup-python@v4
                with:
                  python-version: "3.11"
              - name: Install dependencies
                run: pip install -r backend/requirements.txt
              - name: Run tests
                working-directory: backend
                run: pytest -q
        ```
        
    - **로컬**: Docker Compose로 `.env`에서 환경 변수 주입
    - **CI/CD**: GitHub Secrets로 민감 정보 주입
    - **코드**: `os.getenv("KEY")` 로 안전하게 읽을 수 있습니다.
